version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    dependency-ecosystem: "pip"
    schedule:
      interval: "daily"
      time: "06:00"
    open-pull-requests-limit: 5
    version: "2.0.240"
    directory: "/"
    target-branches:
      - "master"
    updates:
      - package-ecosystem: "pip"
        directory: "/"
        schedule:
          interval: "daily"
        labels:
          - "patch"
          - "minor"
        ignore:
          - dependency-name: "pytest"
            versions: [">=6.0.0a1, <7.0.0"]