language: python
python:
  - "3.5"
# command to install dependencies
install:
 - pip install pipenv
 - pipenv install
 - pipenv install --dev
 - "pipenv run pip install https://github.com/hudsonbrendon/pyudemy/archive/master.zip"

# command to run tests
script: make test
