import pytest

from pyudemy import Udemy


@pytest.fixture
def udemy():
    return Udemy("test", "test")


@pytest.fixture
def course_detail():
    return {
        "_class": "course",
        "id": 4314396,
        "title": "CAREER COACHING FOR YOUR SUCCESS. HOW TO BE A BOSS!",
        "url": "/course/career-coaching-for-your-success-how-to-be-a-boss/",
        "is_paid": True,
        "price": "R$39.90",
        "price_detail": {
            "amount": 39.9,
            "currency": "BRL",
            "price_string": "R$39.90",
            "currency_symbol": "R$",
        },
        "price_serve_tracking_id": "Rga0_GSkTnW43Qo4fSY2UA",
        "visible_instructors": [
            {
                "_class": "user",
                "title": "Mahmoud Affaneh BSN, RN",
                "name": "Mahmoud",
                "display_name": "Mahmoud Affaneh BSN, RN",
                "job_title": "Nursing Education",
                "image_50x50": "https://img-c.udemycdn.com/user/50x50/172537814_896f.jpg",
                "image_100x100": "https://img-c.udemycdn.com/user/100x100/172537814_896f.jpg",
                "initials": "MA",
                "url": "/user/mahmoud-a-9/",
            }
        ],
        "image_125_H": "https://img-c.udemycdn.com/course/125_H/4314396_1ee9.jpg",
        "image_240x135": "https://img-c.udemycdn.com/course/240x135/4314396_1ee9.jpg",
        "is_practice_test_course": False,
        "image_480x270": "https://img-c.udemycdn.com/course/480x270/4314396_1ee9.jpg",
        "published_title": "career-coaching-for-your-success-how-to-be-a-boss",
        "tracking_id": "OeEglPyfTu-AyzZIQ1f5jg",
    }


@pytest.fixture
def course_reviews():
    return {
        "count": 292,
        "next": None,
        "previous": None,
        "results": [
            {
                "_class": "course_review",
                "id": 94380398,
                "content": "",
                "rating": 2.5,
                "created": "2021-09-01T03:17:04Z",
                "modified": "2021-09-02T16:07:58Z",
                "user_modified": "2021-09-01T03:17:11Z",
                "user": {
                    "_class": "user",
                    "title": "Sujitha Arunkumar",
                    "name": "Sujitha",
                    "display_name": "Sujitha Arunkumar",
                },
            },
            {
                "_class": "course_review",
                "id": 93998372,
                "content": "",
                "rating": 4.0,
                "created": "2021-08-27T05:16:12Z",
                "modified": "2021-08-28T16:05:17Z",
                "user_modified": "2021-08-27T05:16:14Z",
                "user": {
                    "_class": "user",
                    "title": "Bruno Rittner",
                    "name": "Bruno",
                    "display_name": "Bruno Rittner",
                },
            },
            {
                "_class": "course_review",
                "id": 93606544,
                "content": "",
                "rating": 4.0,
                "created": "2021-08-23T01:48:48Z",
                "modified": "2021-08-24T16:09:16Z",
                "user_modified": "2021-08-23T01:48:50Z",
                "user": {
                    "_class": "user",
                    "title": "Erdem Oktay",
                    "name": "Erdem",
                    "display_name": "Erdem Oktay",
                },
            },
            {
                "_class": "course_review",
                "id": 90806204,
                "content": "",
                "rating": 4.5,
                "created": "2021-07-20T12:43:05Z",
                "modified": "2021-07-22T16:06:46Z",
                "user_modified": "2021-07-20T12:43:09Z",
                "user": {
                    "_class": "user",
                    "title": "Mohammadamin Ahrabian",
                    "name": "Mohammadamin",
                    "display_name": "Mohammadamin Ahrabian",
                },
            },
            {
                "_class": "course_review",
                "id": 89628066,
                "content": "",
                "rating": 5.0,
                "created": "2021-07-07T03:49:37Z",
                "modified": "2021-07-08T16:06:28Z",
                "user_modified": "2021-07-07T03:49:47Z",
                "user": {
                    "_class": "user",
                    "title": "Shivali Srivastava",
                    "name": "Shivali",
                    "display_name": "Shivali Srivastava",
                },
            },
            {
                "_class": "course_review",
                "id": 88980444,
                "content": "",
                "rating": 5.0,
                "created": "2021-06-29T23:48:51Z",
                "modified": "2021-06-30T16:04:05Z",
                "user_modified": "2021-06-29T23:48:52Z",
                "user": {
                    "_class": "user",
                    "title": "RAJESH BHOKSE",
                    "name": "RAJESH",
                    "display_name": "RAJESH BHOKSE",
                },
            },
            {
                "_class": "course_review",
                "id": 87576380,
                "content": "I learned something new about gaming and 3D game animation creation.",
                "rating": 5.0,
                "created": "2021-06-13T22:15:54Z",
                "modified": "2021-06-14T16:07:57Z",
                "user_modified": "2021-06-13T22:16:28Z",
                "user": {
                    "_class": "user",
                    "title": "Anonymized User",
                    "name": "Anonymized",
                    "display_name": "Anonymized User",
                },
            },
            {
                "_class": "course_review",
                "id": 86383844,
                "content": "good & helpful",
                "rating": 5.0,
                "created": "2021-05-30T23:02:18Z",
                "modified": "2021-05-31T16:04:49Z",
                "user_modified": "2021-05-30T23:02:35Z",
                "user": {
                    "_class": "user",
                    "title": "Ijaz Hassan",
                    "name": "Ijaz",
                    "display_name": "Ijaz Hassan",
                },
            },
            {
                "_class": "course_review",
                "id": 86007208,
                "content": "",
                "rating": 3.0,
                "created": "2021-05-26T10:54:00Z",
                "modified": "2021-05-27T16:04:12Z",
                "user_modified": "2021-05-26T10:54:05Z",
                "user": {
                    "_class": "user",
                    "title": "Jolene",
                    "name": "Jolene",
                    "display_name": "Jolene",
                },
            },
            {
                "_class": "course_review",
                "id": 85614500,
                "content": "",
                "rating": 5.0,
                "created": "2021-05-22T10:08:28Z",
                "modified": "2021-05-23T16:06:36Z",
                "user_modified": "2021-05-22T10:08:29Z",
                "user": {
                    "_class": "user",
                    "title": "Dave L.",
                    "name": "Dave",
                    "display_name": "Dave L.",
                },
            },
        ],
    }


@pytest.fixture
def courses_reviews_with_params():
    return {
        "count": 292,
        "next": "https://www.udemy.com/api-2.0/courses/816772/reviews/?page=2&page_size=1",
        "previous": None,
        "results": [
            {
                "_class": "course_review",
                "id": 94380398,
                "content": "",
                "rating": 2.5,
                "created": "2021-09-01T03:17:04Z",
                "modified": "2021-09-02T16:07:58Z",
                "user_modified": "2021-09-01T03:17:11Z",
                "user": {
                    "_class": "user",
                    "title": "Sujitha Arunkumar",
                    "name": "Sujitha",
                    "display_name": "Sujitha Arunkumar",
                },
            }
        ],
    }


@pytest.fixture
def courses():
    return {
        "count": 10000,
        "next": "https://www.udemy.com/api-2.0/courses/?page=2&page_size=12",
        "previous": None,
        "results": [
            {
                "_class": "course",
                "id": 4314396,
                "title": "CAREER COACHING FOR YOUR SUCCESS. HOW TO BE A BOSS!",
                "url": "/course/career-coaching-for-your-success-how-to-be-a-boss/",
                "is_paid": True,
                "price": "R$39.90",
                "price_detail": {
                    "currency": "BRL",
                    "currency_symbol": "R$",
                    "price_string": "R$39.90",
                    "amount": 39.9,
                },
                "price_serve_tracking_id": "uvOIl28PTLiuCFlCyeuISQ",
                "visible_instructors": [
                    {
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/172537814_896f.jpg",
                        "initials": "MA",
                        "job_title": "Nursing Education",
                        "title": "Mahmoud Affaneh BSN, RN",
                        "url": "/user/mahmoud-a-9/",
                        "_class": "user",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/172537814_896f.jpg",
                        "name": "Mahmoud",
                        "display_name": "Mahmoud Affaneh BSN, RN",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/4314396_1ee9.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/4314396_1ee9.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/4314396_1ee9.jpg",
                "published_title": "career-coaching-for-your-success-how-to-be-a-boss",
                "tracking_id": "KWTNiNFsRrOAe-CyFGvKUQ",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Career Guidance",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 4307533,
                "title": "Certified in Information System Audit (CISA 3)",
                "url": "/course/certified-in-information-system-audit-cisa-3/",
                "is_paid": True,
                "price": "R$39.90",
                "price_detail": {
                    "amount": 39.9,
                    "currency": "BRL",
                    "price_string": "R$39.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "SikSF7QcTauQdMgDWUbDHw",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "First Step Training",
                        "name": "First Step",
                        "display_name": "First Step Training",
                        "job_title": "Project Management Consultant",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/85332568_c7e9_2.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/85332568_c7e9_2.jpg",
                        "initials": "FT",
                        "url": "/user/sherif-hussein-16/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/4307533_26e2_2.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/4307533_26e2_2.jpg",
                "is_practice_test_course": True,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/4307533_26e2_2.jpg",
                "published_title": "certified-in-information-system-audit-cisa-3",
                "tracking_id": "FykcW9zzSNeGddOrQxLXug",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Highly Reliable CISA Mock Exams",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 683360,
                "title": "Neo4j : A NOSQL database from scratch",
                "url": "/course/neo4j-a-nosql-database-from-scratch/",
                "is_paid": True,
                "price": "R$189.90",
                "price_detail": {
                    "amount": 189.9,
                    "currency": "BRL",
                    "price_string": "R$189.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "3sjwmtSLTGyH3NQYdkgZTQ",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Edionik Solutions",
                        "name": "Edionik",
                        "display_name": "Edionik Solutions",
                        "job_title": "Serving Technology Simply",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/2214188_ec6e_4.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/2214188_ec6e_4.jpg",
                        "initials": "ES",
                        "url": "/user/shubhamgupta14/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/683360_9446_3.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/683360_9446_3.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/683360_9446_3.jpg",
                "published_title": "neo4j-a-nosql-database-from-scratch",
                "tracking_id": "1mu4I1F4Q9e9B1-KUsGnmw",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Learn Neo4j Graph Database from a beginner point of view",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 684794,
                "title": "Build Web Apps Using EmberJS: The Complete Course",
                "url": "/course/build-web-apps-using-emberjs-the-complete-course/",
                "is_paid": True,
                "price": "R$99.90",
                "price_detail": {
                    "amount": 99.9,
                    "currency": "BRL",
                    "price_string": "R$99.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "x5gRje4kQWi9MtKZKSp_nA",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Eduonix Learning Solutions",
                        "name": "Eduonix",
                        "display_name": "Eduonix Learning Solutions",
                        "job_title": "1+ Million Students Worldwide | 200+ Courses",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/598757_b22a_3.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/598757_b22a_3.jpg",
                        "initials": "EL",
                        "url": "/user/eduonix/",
                    },
                    {
                        "_class": "user",
                        "title": "Eduonix-Tech .",
                        "name": "Eduonix-Tech",
                        "display_name": "Eduonix-Tech .",
                        "job_title": "",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/anonymous_3.png",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/anonymous_3.png",
                        "initials": "E.",
                        "url": "/user/eduonix-tech/",
                    },
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/684794_b6ff_3.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/684794_b6ff_3.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/684794_b6ff_3.jpg",
                "published_title": "build-web-apps-using-emberjs-the-complete-course",
                "tracking_id": "qn4X36y2TaSnqHj2hY7A5g",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Learn to develop web apps using Ember JS",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 688432,
                "title": "Anger Management Techniques That Actually Work",
                "url": "/course/howtocontrolanger/",
                "is_paid": True,
                "price": "R$204.90",
                "price_detail": {
                    "amount": 204.9,
                    "currency": "BRL",
                    "price_string": "R$204.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "4_J2zqcwTw2EPmHkGGph_w",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Ken Wells",
                        "name": "Ken",
                        "display_name": "Ken Wells",
                        "job_title": "Best-Selling Instructor 74,140+ Students in 182 Countries",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/8036240_2ef6_6.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/8036240_2ef6_6.jpg",
                        "initials": "KW",
                        "url": "/user/kenwells5/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/688432_307e_4.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/688432_307e_4.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/688432_307e_4.jpg",
                "published_title": "howtocontrolanger",
                "tracking_id": "-xMyyCdzRhephEIZ-wqG1w",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "How to Control Anger so You Can Feel Good, Have Better Relationships and Reduce Stress - Anger Management Techniques",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 691780,
                "title": "Data Structures in C++",
                "url": "/course/datastructures/",
                "is_paid": True,
                "price": "R$39.90",
                "price_detail": {
                    "amount": 39.9,
                    "currency": "BRL",
                    "price_string": "R$39.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "wCUECm5eR6WIZU9K3V9wQg",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Nisha Kiran",
                        "name": "Nisha",
                        "display_name": "Nisha Kiran",
                        "job_title": "Instructor",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/5265928_2bcf.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/5265928_2bcf.jpg",
                        "initials": "NK",
                        "url": "/user/nishakiran/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/691780_aadc_3.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/691780_aadc_3.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/691780_aadc_3.jpg",
                "published_title": "datastructures",
                "tracking_id": "9f157_F4RaapK6GYNJ2_ww",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Learn and master the popular data structures in C++",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 693476,
                "title": "2d Bitmap art for video games",
                "url": "/course/2d-bitmap-art-for-video-games/",
                "is_paid": True,
                "price": "R$84.90",
                "price_detail": {
                    "amount": 84.9,
                    "currency": "BRL",
                    "price_string": "R$84.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "mhjRwXNuQMKJjQ9kp50hsg",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Marco Vale",
                        "name": "Marco",
                        "display_name": "Marco Vale",
                        "job_title": "Game Artist",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/3184564_8f35_2.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/3184564_8f35_2.jpg",
                        "initials": "MV",
                        "url": "/user/marcovale/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/693476_0f5b.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/693476_0f5b.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/693476_0f5b.jpg",
                "published_title": "2d-bitmap-art-for-video-games",
                "tracking_id": "932dsU90SW6c2oUwB0ZKfg",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Learn how to create top quality graphics for your games and designs",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 694982,
                "title": "Rest API Testing (Automation) from Scratch-Rest Assured Java",
                "url": "/course/rest-api-automation-testing-rest-assured/",
                "is_paid": True,
                "price": "R$219.90",
                "price_detail": {
                    "amount": 219.9,
                    "currency": "BRL",
                    "price_string": "R$219.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "nLlGXJgxR2GSuVMQBjwO0g",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Rahul Shetty",
                        "name": "Rahul",
                        "display_name": "Rahul Shetty",
                        "job_title": "Founder of RahulShettyAcademy.com|350k+ QA Students",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/5997742_a60f_51.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/5997742_a60f_51.jpg",
                        "initials": "RS",
                        "url": "/user/rahul445/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/694982_33b0.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/694982_33b0.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/694982_33b0.jpg",
                "published_title": "rest-api-automation-testing-rest-assured",
                "tracking_id": "lh6mxjNERIyhgT41uoWmsQ",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": '"Top Ranked #1 Rest API Test Automation & postman tutorial with Java from Basics to Framework with Real time examples',
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 697782,
                "title": "How To Sell More By Becoming A Better Copywriter",
                "url": "/course/copywriting-secrets-start-your-own-copywriting-journey/",
                "is_paid": True,
                "price": "R$189.90",
                "price_detail": {
                    "amount": 189.9,
                    "currency": "BRL",
                    "price_string": "R$189.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "bWRb9SgFTauBiRxWYroX6g",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Kevin Farrugia",
                        "name": "Kevin",
                        "display_name": "Kevin Farrugia",
                        "job_title": "EFL English Teacher",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/4929782_f69d_3.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/4929782_f69d_3.jpg",
                        "initials": "KF",
                        "url": "/user/kevinfarrugia3/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/697782_f182_2.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/697782_f182_2.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/697782_f182_2.jpg",
                "published_title": "copywriting-secrets-start-your-own-copywriting-journey",
                "tracking_id": "xOgDPfroRbGv77xQdLEl0w",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Learn the secrets that make people buy & how to tap into these secrets to increase your bottom line through copywriting",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 699236,
                "title": "Beginner Guitar Lessons - Learn EASY SONGS on the Guitar",
                "url": "/course/guitar-lessons-easy-songs-on-the-guitar/",
                "is_paid": True,
                "price": "R$39.90",
                "price_detail": {
                    "amount": 39.9,
                    "currency": "BRL",
                    "price_string": "R$39.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "-P0hZ5ozTZ2eSiaJf-3J0A",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Lesson Pros",
                        "name": "Lesson",
                        "display_name": "Lesson Pros",
                        "job_title": "Award Winning Instructors, 100,000+ students",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/13721614_a1de_5.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/13721614_a1de_5.jpg",
                        "initials": "LP",
                        "url": "/user/sandimillar/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/699236_c1b7_7.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/699236_c1b7_7.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/699236_c1b7_7.jpg",
                "published_title": "guitar-lessons-easy-songs-on-the-guitar",
                "tracking_id": "3tzvvMpmQjqVsMkYU1R5ow",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Beginner Guitar Lessons - Easy Guitar Songs - Beginner Guitar Songs - Beginner Guitar Lessons - Learn Beginner Guitar",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 709288,
                "title": "Salesforce Change and Release Management - A complete guide",
                "url": "/course/salesforce-change-and-release-management-a-complete-guide/",
                "is_paid": True,
                "price": "R$189.90",
                "price_detail": {
                    "amount": 189.9,
                    "currency": "BRL",
                    "price_string": "R$189.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "YuyR9Iz6Q-Oh-jZY9sRxdg",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Archana Rajendran",
                        "name": "Archana",
                        "display_name": "Archana Rajendran",
                        "job_title": "Salesforce Technical Consultant",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/15987318_4540.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/15987318_4540.jpg",
                        "initials": "AR",
                        "url": "/user/archana-rajendran/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/709288_78e2_4.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/709288_78e2_4.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/709288_78e2_4.jpg",
                "published_title": "salesforce-change-and-release-management-a-complete-guide",
                "tracking_id": "FoLQkTmxRSGaL7mQkhFqzg",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Become an expert in handling Salesforce metadata changes and deployment across orgs",
                "instructor_name": None,
            },
            {
                "_class": "course",
                "id": 710654,
                "title": "Read Music Fast! Sight Reading Trick - Jin's Theory",
                "url": "/course/read-music-fast-sight-reading-trick-jins-theory/",
                "is_paid": True,
                "price": "R$39.90",
                "price_detail": {
                    "amount": 39.9,
                    "currency": "BRL",
                    "price_string": "R$39.90",
                    "currency_symbol": "R$",
                },
                "price_serve_tracking_id": "Xh-TwHgnTPStL6sEzkDfsQ",
                "visible_instructors": [
                    {
                        "_class": "user",
                        "title": "Yanjin Luo",
                        "name": "Yanjin",
                        "display_name": "Yanjin Luo",
                        "job_title": "A Passionate Music Teacher",
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/19027798_070f.jpg",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/19027798_070f.jpg",
                        "initials": "YL",
                        "url": "/user/yanjin-luo/",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/710654_7668_5.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/710654_7668_5.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/710654_7668_5.jpg",
                "published_title": "read-music-fast-sight-reading-trick-jins-theory",
                "tracking_id": "RklLl-Y0SGq3VAbsZPKPjw",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Learn reading music notes techniques; Change your way to practice sight reading",
                "instructor_name": None,
            },
        ],
        "aggregations": [
            {
                "options": [
                    {
                        "count": 10000,
                        "key": "price",
                        "title": "Paid",
                        "value": "price-paid",
                    },
                    {
                        "count": 10000,
                        "key": "price",
                        "title": "Free",
                        "value": "price-free",
                    },
                ],
                "title": "Price",
                "id": "price",
            },
            {
                "options": [
                    {
                        "count": 10000,
                        "key": "instructional_level",
                        "title": "All Levels",
                        "value": "all",
                    },
                    {
                        "count": 10000,
                        "key": "instructional_level",
                        "title": "Beginner",
                        "value": "beginner",
                    },
                    {
                        "count": 10000,
                        "key": "instructional_level",
                        "title": "Intermediate",
                        "value": "intermediate",
                    },
                    {
                        "count": 3596,
                        "key": "instructional_level",
                        "title": "Expert",
                        "value": "expert",
                    },
                ],
                "title": "Level",
                "id": "instructional_level",
            },
            {
                "options": [
                    {
                        "count": 10000,
                        "key": "has_closed_caption",
                        "title": "Captions",
                        "value": "True",
                    },
                    {
                        "count": 10000,
                        "key": "has_simple_quiz",
                        "title": "Quizzes",
                        "value": "True",
                    },
                    {
                        "count": 776,
                        "key": "has_coding_exercises",
                        "title": "Coding Exercises",
                        "value": "True",
                    },
                ],
                "title": "Features",
                "id": "features",
            },
            {
                "options": [
                    {
                        "count": 10000,
                        "key": "language",
                        "title": "English",
                        "value": "en",
                    },
                    {
                        "count": 10000,
                        "key": "language",
                        "title": "Português",
                        "value": "pt",
                    },
                    {
                        "count": 10000,
                        "key": "language",
                        "title": "Español",
                        "value": "es",
                    },
                    {
                        "count": 6414,
                        "key": "language",
                        "title": "Türkçe",
                        "value": "tr",
                    },
                    {
                        "count": 4979,
                        "key": "language",
                        "title": "日本語",
                        "value": "ja",
                    },
                    {
                        "count": 4975,
                        "key": "language",
                        "title": "Deutsch",
                        "value": "de",
                    },
                    {
                        "count": 4372,
                        "key": "language",
                        "title": "Français",
                        "value": "fr",
                    },
                    {
                        "count": 3831,
                        "key": "language",
                        "title": "العربية",
                        "value": "ar",
                    },
                    {
                        "count": 2962,
                        "key": "language",
                        "title": "Italiano",
                        "value": "it",
                    },
                    {
                        "count": 2228,
                        "key": "language",
                        "title": "Русский",
                        "value": "ru",
                    },
                    {
                        "count": 1628,
                        "key": "language",
                        "title": "中文",
                        "value": "zh",
                    },
                    {
                        "count": 1268,
                        "key": "language",
                        "title": "हिन्दी",
                        "value": "hi",
                    },
                    {
                        "count": 1260,
                        "key": "language",
                        "title": "Polski",
                        "value": "pl",
                    },
                    {
                        "count": 1045,
                        "key": "language",
                        "title": "Bahasa Indonesia",
                        "value": "id",
                    },
                    {
                        "count": 608,
                        "key": "language",
                        "title": "한국어",
                        "value": "ko",
                    },
                    {
                        "count": 373,
                        "key": "language",
                        "title": "اردو",
                        "value": "ur",
                    },
                    {
                        "count": 253,
                        "key": "language",
                        "title": "ภาษาไทย",
                        "value": "th",
                    },
                    {
                        "count": 227,
                        "key": "language",
                        "title": "Română",
                        "value": "ro",
                    },
                    {
                        "count": 224,
                        "key": "language",
                        "title": "தமிழ்",
                        "value": "ta",
                    },
                    {
                        "count": 186,
                        "key": "language",
                        "title": "Nederlands",
                        "value": "nl",
                    },
                    {
                        "count": 162,
                        "key": "language",
                        "title": "‏עברית‏",
                        "value": "he",
                    },
                    {
                        "count": 113,
                        "key": "language",
                        "title": "Tiếng Việt",
                        "value": "vi",
                    },
                    {
                        "count": 109,
                        "key": "language",
                        "title": "Magyar",
                        "value": "hu",
                    },
                    {
                        "count": 100,
                        "key": "language",
                        "title": "Ελληνικά",
                        "value": "el",
                    },
                    {
                        "count": 76,
                        "key": "language",
                        "title": "Telugu",
                        "value": "te",
                    },
                    {
                        "count": 67,
                        "key": "language",
                        "title": "Bangla",
                        "value": "bn",
                    },
                    {
                        "count": 61,
                        "key": "language",
                        "title": "Azərbaycan dili",
                        "value": "az",
                    },
                    {
                        "count": 59,
                        "key": "language",
                        "title": "मराठी",
                        "value": "mr",
                    },
                    {
                        "count": 46,
                        "key": "language",
                        "title": "Malayāḷam",
                        "value": "ml",
                    },
                    {
                        "count": 39,
                        "key": "language",
                        "title": "فارسی",
                        "value": "fa",
                    },
                    {
                        "count": 26,
                        "key": "language",
                        "title": "Afrikaans",
                        "value": "af",
                    },
                    {
                        "count": 24,
                        "key": "language",
                        "title": "Українська",
                        "value": "uk",
                    },
                    {
                        "count": 23,
                        "key": "language",
                        "title": "Hrvatski",
                        "value": "hr",
                    },
                    {
                        "count": 18,
                        "key": "language",
                        "title": "Svenska",
                        "value": "sv",
                    },
                    {
                        "count": 17,
                        "key": "language",
                        "title": "Čeština",
                        "value": "cs",
                    },
                    {
                        "count": 17,
                        "key": "language",
                        "title": "ગુજરાતી",
                        "value": "gu",
                    },
                    {
                        "count": 17,
                        "key": "language",
                        "title": "Српски",
                        "value": "sr",
                    },
                    {
                        "count": 16,
                        "key": "language",
                        "title": "Български",
                        "value": "bg",
                    },
                    {
                        "count": 15,
                        "key": "language",
                        "title": "Norsk",
                        "value": "nb",
                    },
                    {
                        "count": 14,
                        "key": "language",
                        "title": "မြန်မာဘာသာ",
                        "value": "my",
                    },
                    {
                        "count": 12,
                        "key": "language",
                        "title": "Suomi",
                        "value": "fi",
                    },
                    {
                        "count": 11,
                        "key": "language",
                        "title": "Eesti",
                        "value": "et",
                    },
                    {
                        "count": 11,
                        "key": "language",
                        "title": "Kannaḍa",
                        "value": "kn",
                    },
                    {
                        "count": 10,
                        "key": "language",
                        "title": "Bahasa Melayu",
                        "value": "ms",
                    },
                    {
                        "count": 10,
                        "key": "language",
                        "title": "नेपाली",
                        "value": "ne",
                    },
                    {
                        "count": 9,
                        "key": "language",
                        "title": "Dansk",
                        "value": "da",
                    },
                    {
                        "count": 9,
                        "key": "language",
                        "title": "Shqip",
                        "value": "sq",
                    },
                    {
                        "count": 8,
                        "key": "language",
                        "title": "Filipino",
                        "value": "tl",
                    },
                    {
                        "count": 8,
                        "key": "language",
                        "title": "O'zbek",
                        "value": "uz",
                    },
                    {
                        "count": 7,
                        "key": "language",
                        "title": "Català",
                        "value": "ca",
                    },
                    {
                        "count": 7,
                        "key": "language",
                        "title": "ქართული",
                        "value": "ka",
                    },
                    {
                        "count": 7,
                        "key": "language",
                        "title": "Latviešu",
                        "value": "lv",
                    },
                    {
                        "count": 7,
                        "key": "language",
                        "title": "Soomaaliga",
                        "value": "so",
                    },
                    {
                        "count": 6,
                        "key": "language",
                        "title": "Қазақша",
                        "value": "kk",
                    },
                    {
                        "count": 5,
                        "key": "language",
                        "title": "Lietuvių",
                        "value": "lt",
                    },
                    {
                        "count": 4,
                        "key": "language",
                        "title": "Gaeilge",
                        "value": "ga",
                    },
                    {
                        "count": 4,
                        "key": "language",
                        "title": "ਪੰਜਾਬੀ",
                        "value": "pa",
                    },
                    {
                        "count": 4,
                        "key": "language",
                        "title": "Kiswahili",
                        "value": "sw",
                    },
                    {
                        "count": 3,
                        "key": "language",
                        "title": "Македонски",
                        "value": "mk",
                    },
                    {
                        "count": 3,
                        "key": "language",
                        "title": "Монгол",
                        "value": "mn",
                    },
                    {
                        "count": 3,
                        "key": "language",
                        "title": "پښتو",
                        "value": "ps",
                    },
                    {
                        "count": 3,
                        "key": "language",
                        "title": "Slovenčina",
                        "value": "sk",
                    },
                    {
                        "count": 2,
                        "key": "language",
                        "title": "Հայերեն",
                        "value": "hy",
                    },
                    {
                        "count": 2,
                        "key": "language",
                        "title": "Kurdî",
                        "value": "ku",
                    },
                    {
                        "count": 2,
                        "key": "language",
                        "title": "Slovenščina",
                        "value": "sl",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "Aymar aru",
                        "value": "ay",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "Cymraeg",
                        "value": "cy",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "Euskara",
                        "value": "eu",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "Føroyskt",
                        "value": "fo",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "Avañe'ẽ",
                        "value": "gn",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "Ayisyen",
                        "value": "ht",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "Khmer",
                        "value": "km",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "Qhichwa",
                        "value": "qu",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "тоҷикӣ, تاجیکی‎, tojikī",
                        "value": "tg",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "татарча / Tatarça / تاتارچا",
                        "value": "tt",
                    },
                    {
                        "count": 1,
                        "key": "language",
                        "title": "isiZulu",
                        "value": "zu",
                    },
                ],
                "title": "Language",
                "id": "language",
            },
            {
                "options": [
                    {
                        "count": 10000,
                        "key": "ratings",
                        "title": "4.5 & up",
                        "value": "4.5",
                    },
                    {
                        "count": 10000,
                        "key": "ratings",
                        "title": "4.0 & up",
                        "value": "4.0",
                    },
                    {
                        "count": 10000,
                        "key": "ratings",
                        "title": "3.5 & up",
                        "value": "3.5",
                    },
                    {
                        "count": 10000,
                        "key": "ratings",
                        "title": "3.0 & up",
                        "value": "3.0",
                    },
                ],
                "title": "Ratings",
                "id": "ratings",
            },
            {
                "options": [
                    {
                        "count": 10000,
                        "key": "duration",
                        "title": "0-1 Hour",
                        "value": "extraShort",
                    },
                    {
                        "count": 10000,
                        "key": "duration",
                        "title": "1-3 Hours",
                        "value": "short",
                    },
                    {
                        "count": 10000,
                        "key": "duration",
                        "title": "3-6 Hours",
                        "value": "medium",
                    },
                    {
                        "count": 10000,
                        "key": "duration",
                        "title": "6-17 Hours",
                        "value": "long",
                    },
                    {
                        "count": 7238,
                        "key": "duration",
                        "title": "17+ Hours",
                        "value": "extraLong",
                    },
                ],
                "title": "Duration",
                "id": "duration",
            },
        ],
        "search_tracking_id": "Gd9lRBUMQwuyVMvGfbKxDg",
    }


@pytest.fixture
def courses_with_params():
    return {
        "count": 10000,
        "next": "https://www.udemy.com/api-2.0/courses/?page=2&page_size=1",
        "previous": None,
        "results": [
            {
                "_class": "course",
                "id": 4314396,
                "title": "CAREER COACHING FOR YOUR SUCCESS. HOW TO BE A BOSS!",
                "url": "/course/career-coaching-for-your-success-how-to-be-a-boss/",
                "is_paid": True,
                "price": "R$39.90",
                "price_detail": {
                    "currency": "BRL",
                    "currency_symbol": "R$",
                    "amount": 39.9,
                    "price_string": "R$39.90",
                },
                "price_serve_tracking_id": "uvOIl28PTLiuCFlCyeuISQ",
                "visible_instructors": [
                    {
                        "image_50x50": "https://img-c.udemycdn.com/user/50x50/172537814_896f.jpg",
                        "url": "/user/mahmoud-a-9/",
                        "initials": "MA",
                        "name": "Mahmoud",
                        "image_100x100": "https://img-c.udemycdn.com/user/100x100/172537814_896f.jpg",
                        "job_title": "Nursing Education",
                        "_class": "user",
                        "title": "Mahmoud Affaneh BSN, RN",
                        "display_name": "Mahmoud Affaneh BSN, RN",
                    }
                ],
                "image_125_H": "https://img-c.udemycdn.com/course/125_H/4314396_1ee9.jpg",
                "image_240x135": "https://img-c.udemycdn.com/course/240x135/4314396_1ee9.jpg",
                "is_practice_test_course": False,
                "image_480x270": "https://img-c.udemycdn.com/course/480x270/4314396_1ee9.jpg",
                "published_title": "career-coaching-for-your-success-how-to-be-a-boss",
                "tracking_id": "-6uOenOfQnCFafhPuf0wPw",
                "predictive_score": None,
                "relevancy_score": None,
                "input_features": None,
                "lecture_search_result": None,
                "curriculum_lectures": [],
                "order_in_results": None,
                "curriculum_items": [],
                "headline": "Career Guidance",
                "instructor_name": None,
            }
        ],
        "aggregations": [
            {
                "title": "Price",
                "id": "price",
                "options": [
                    {
                        "value": "price-paid",
                        "key": "price",
                        "count": 10000,
                        "title": "Paid",
                    },
                    {
                        "value": "price-free",
                        "key": "price",
                        "count": 10000,
                        "title": "Free",
                    },
                ],
            },
            {
                "title": "Level",
                "id": "instructional_level",
                "options": [
                    {
                        "value": "all",
                        "key": "instructional_level",
                        "count": 10000,
                        "title": "All Levels",
                    },
                    {
                        "value": "beginner",
                        "key": "instructional_level",
                        "count": 10000,
                        "title": "Beginner",
                    },
                    {
                        "value": "intermediate",
                        "key": "instructional_level",
                        "count": 10000,
                        "title": "Intermediate",
                    },
                    {
                        "value": "expert",
                        "key": "instructional_level",
                        "count": 3596,
                        "title": "Expert",
                    },
                ],
            },
            {
                "title": "Features",
                "id": "features",
                "options": [
                    {
                        "value": "True",
                        "key": "has_closed_caption",
                        "count": 10000,
                        "title": "Captions",
                    },
                    {
                        "value": "True",
                        "key": "has_simple_quiz",
                        "count": 10000,
                        "title": "Quizzes",
                    },
                    {
                        "value": "True",
                        "key": "has_coding_exercises",
                        "count": 776,
                        "title": "Coding Exercises",
                    },
                ],
            },
            {
                "title": "Language",
                "id": "language",
                "options": [
                    {
                        "value": "en",
                        "key": "language",
                        "count": 10000,
                        "title": "English",
                    },
                    {
                        "value": "pt",
                        "key": "language",
                        "count": 10000,
                        "title": "Português",
                    },
                    {
                        "value": "es",
                        "key": "language",
                        "count": 10000,
                        "title": "Español",
                    },
                    {
                        "value": "tr",
                        "key": "language",
                        "count": 6414,
                        "title": "Türkçe",
                    },
                    {
                        "value": "ja",
                        "key": "language",
                        "count": 4979,
                        "title": "日本語",
                    },
                    {
                        "value": "de",
                        "key": "language",
                        "count": 4975,
                        "title": "Deutsch",
                    },
                    {
                        "value": "fr",
                        "key": "language",
                        "count": 4372,
                        "title": "Français",
                    },
                    {
                        "value": "ar",
                        "key": "language",
                        "count": 3831,
                        "title": "العربية",
                    },
                    {
                        "value": "it",
                        "key": "language",
                        "count": 2962,
                        "title": "Italiano",
                    },
                    {
                        "value": "ru",
                        "key": "language",
                        "count": 2228,
                        "title": "Русский",
                    },
                    {
                        "value": "zh",
                        "key": "language",
                        "count": 1628,
                        "title": "中文",
                    },
                    {
                        "value": "hi",
                        "key": "language",
                        "count": 1268,
                        "title": "हिन्दी",
                    },
                    {
                        "value": "pl",
                        "key": "language",
                        "count": 1260,
                        "title": "Polski",
                    },
                    {
                        "value": "id",
                        "key": "language",
                        "count": 1045,
                        "title": "Bahasa Indonesia",
                    },
                    {
                        "value": "ko",
                        "key": "language",
                        "count": 608,
                        "title": "한국어",
                    },
                    {
                        "value": "ur",
                        "key": "language",
                        "count": 373,
                        "title": "اردو",
                    },
                    {
                        "value": "th",
                        "key": "language",
                        "count": 253,
                        "title": "ภาษาไทย",
                    },
                    {
                        "value": "ro",
                        "key": "language",
                        "count": 227,
                        "title": "Română",
                    },
                    {
                        "value": "ta",
                        "key": "language",
                        "count": 224,
                        "title": "தமிழ்",
                    },
                    {
                        "value": "nl",
                        "key": "language",
                        "count": 186,
                        "title": "Nederlands",
                    },
                    {
                        "value": "he",
                        "key": "language",
                        "count": 162,
                        "title": "‏עברית‏",
                    },
                    {
                        "value": "vi",
                        "key": "language",
                        "count": 113,
                        "title": "Tiếng Việt",
                    },
                    {
                        "value": "hu",
                        "key": "language",
                        "count": 109,
                        "title": "Magyar",
                    },
                    {
                        "value": "el",
                        "key": "language",
                        "count": 100,
                        "title": "Ελληνικά",
                    },
                    {
                        "value": "te",
                        "key": "language",
                        "count": 76,
                        "title": "Telugu",
                    },
                    {
                        "value": "bn",
                        "key": "language",
                        "count": 67,
                        "title": "Bangla",
                    },
                    {
                        "value": "az",
                        "key": "language",
                        "count": 61,
                        "title": "Azərbaycan dili",
                    },
                    {
                        "value": "mr",
                        "key": "language",
                        "count": 59,
                        "title": "मराठी",
                    },
                    {
                        "value": "ml",
                        "key": "language",
                        "count": 46,
                        "title": "Malayāḷam",
                    },
                    {
                        "value": "fa",
                        "key": "language",
                        "count": 39,
                        "title": "فارسی",
                    },
                    {
                        "value": "af",
                        "key": "language",
                        "count": 26,
                        "title": "Afrikaans",
                    },
                    {
                        "value": "uk",
                        "key": "language",
                        "count": 24,
                        "title": "Українська",
                    },
                    {
                        "value": "hr",
                        "key": "language",
                        "count": 23,
                        "title": "Hrvatski",
                    },
                    {
                        "value": "sv",
                        "key": "language",
                        "count": 18,
                        "title": "Svenska",
                    },
                    {
                        "value": "cs",
                        "key": "language",
                        "count": 17,
                        "title": "Čeština",
                    },
                    {
                        "value": "gu",
                        "key": "language",
                        "count": 17,
                        "title": "ગુજરાતી",
                    },
                    {
                        "value": "sr",
                        "key": "language",
                        "count": 17,
                        "title": "Српски",
                    },
                    {
                        "value": "bg",
                        "key": "language",
                        "count": 16,
                        "title": "Български",
                    },
                    {
                        "value": "nb",
                        "key": "language",
                        "count": 15,
                        "title": "Norsk",
                    },
                    {
                        "value": "my",
                        "key": "language",
                        "count": 14,
                        "title": "မြန်မာဘာသာ",
                    },
                    {
                        "value": "fi",
                        "key": "language",
                        "count": 12,
                        "title": "Suomi",
                    },
                    {
                        "value": "et",
                        "key": "language",
                        "count": 11,
                        "title": "Eesti",
                    },
                    {
                        "value": "kn",
                        "key": "language",
                        "count": 11,
                        "title": "Kannaḍa",
                    },
                    {
                        "value": "ms",
                        "key": "language",
                        "count": 10,
                        "title": "Bahasa Melayu",
                    },
                    {
                        "value": "ne",
                        "key": "language",
                        "count": 10,
                        "title": "नेपाली",
                    },
                    {
                        "value": "da",
                        "key": "language",
                        "count": 9,
                        "title": "Dansk",
                    },
                    {
                        "value": "sq",
                        "key": "language",
                        "count": 9,
                        "title": "Shqip",
                    },
                    {
                        "value": "tl",
                        "key": "language",
                        "count": 8,
                        "title": "Filipino",
                    },
                    {
                        "value": "uz",
                        "key": "language",
                        "count": 8,
                        "title": "O'zbek",
                    },
                    {
                        "value": "ca",
                        "key": "language",
                        "count": 7,
                        "title": "Català",
                    },
                    {
                        "value": "ka",
                        "key": "language",
                        "count": 7,
                        "title": "ქართული",
                    },
                    {
                        "value": "lv",
                        "key": "language",
                        "count": 7,
                        "title": "Latviešu",
                    },
                    {
                        "value": "so",
                        "key": "language",
                        "count": 7,
                        "title": "Soomaaliga",
                    },
                    {
                        "value": "kk",
                        "key": "language",
                        "count": 6,
                        "title": "Қазақша",
                    },
                    {
                        "value": "lt",
                        "key": "language",
                        "count": 5,
                        "title": "Lietuvių",
                    },
                    {
                        "value": "ga",
                        "key": "language",
                        "count": 4,
                        "title": "Gaeilge",
                    },
                    {
                        "value": "pa",
                        "key": "language",
                        "count": 4,
                        "title": "ਪੰਜਾਬੀ",
                    },
                    {
                        "value": "sw",
                        "key": "language",
                        "count": 4,
                        "title": "Kiswahili",
                    },
                    {
                        "value": "mk",
                        "key": "language",
                        "count": 3,
                        "title": "Македонски",
                    },
                    {
                        "value": "mn",
                        "key": "language",
                        "count": 3,
                        "title": "Монгол",
                    },
                    {
                        "value": "ps",
                        "key": "language",
                        "count": 3,
                        "title": "پښتو",
                    },
                    {
                        "value": "sk",
                        "key": "language",
                        "count": 3,
                        "title": "Slovenčina",
                    },
                    {
                        "value": "hy",
                        "key": "language",
                        "count": 2,
                        "title": "Հայերեն",
                    },
                    {
                        "value": "ku",
                        "key": "language",
                        "count": 2,
                        "title": "Kurdî",
                    },
                    {
                        "value": "sl",
                        "key": "language",
                        "count": 2,
                        "title": "Slovenščina",
                    },
                    {
                        "value": "ay",
                        "key": "language",
                        "count": 1,
                        "title": "Aymar aru",
                    },
                    {
                        "value": "cy",
                        "key": "language",
                        "count": 1,
                        "title": "Cymraeg",
                    },
                    {
                        "value": "eu",
                        "key": "language",
                        "count": 1,
                        "title": "Euskara",
                    },
                    {
                        "value": "fo",
                        "key": "language",
                        "count": 1,
                        "title": "Føroyskt",
                    },
                    {
                        "value": "gn",
                        "key": "language",
                        "count": 1,
                        "title": "Avañe'ẽ",
                    },
                    {
                        "value": "ht",
                        "key": "language",
                        "count": 1,
                        "title": "Ayisyen",
                    },
                    {
                        "value": "km",
                        "key": "language",
                        "count": 1,
                        "title": "Khmer",
                    },
                    {
                        "value": "qu",
                        "key": "language",
                        "count": 1,
                        "title": "Qhichwa",
                    },
                    {
                        "value": "tg",
                        "key": "language",
                        "count": 1,
                        "title": "тоҷикӣ, تاجیکی‎, tojikī",
                    },
                    {
                        "value": "tt",
                        "key": "language",
                        "count": 1,
                        "title": "татарча / Tatarça / تاتارچا",
                    },
                    {
                        "value": "zu",
                        "key": "language",
                        "count": 1,
                        "title": "isiZulu",
                    },
                ],
            },
            {
                "title": "Ratings",
                "id": "ratings",
                "options": [
                    {
                        "value": "4.5",
                        "key": "ratings",
                        "count": 10000,
                        "title": "4.5 & up",
                    },
                    {
                        "value": "4.0",
                        "key": "ratings",
                        "count": 10000,
                        "title": "4.0 & up",
                    },
                    {
                        "value": "3.5",
                        "key": "ratings",
                        "count": 10000,
                        "title": "3.5 & up",
                    },
                    {
                        "value": "3.0",
                        "key": "ratings",
                        "count": 10000,
                        "title": "3.0 & up",
                    },
                ],
            },
            {
                "title": "Duration",
                "id": "duration",
                "options": [
                    {
                        "value": "extraShort",
                        "key": "duration",
                        "count": 10000,
                        "title": "0-1 Hour",
                    },
                    {
                        "value": "short",
                        "key": "duration",
                        "count": 10000,
                        "title": "1-3 Hours",
                    },
                    {
                        "value": "medium",
                        "key": "duration",
                        "count": 10000,
                        "title": "3-6 Hours",
                    },
                    {
                        "value": "long",
                        "key": "duration",
                        "count": 10000,
                        "title": "6-17 Hours",
                    },
                    {
                        "value": "extraLong",
                        "key": "duration",
                        "count": 7238,
                        "title": "17+ Hours",
                    },
                ],
            },
        ],
        "search_tracking_id": "StNftHLqSd6kbpEyNDrGDA",
    }


@pytest.fixture
def public_curriculum():
    return {
        "count": 3,
        "next": None,
        "previous": None,
        "results": [
            {
                "_class": "chapter",
                "id": 542756,
                "created": "2014-12-05T18:54:27Z",
                "sort_order": 4,
                "title": "My First Section",
                "description": None,
                "is_published": True,
            },
            {
                "_class": "lecture",
                "id": 59955,
                "title": "Ella Y Yo",
                "created": "2012-01-04T10:12:51Z",
                "description": "",
                "title_cleaned": "ella-y-yo",
                "is_published": True,
                "transcript": None,
                "is_downloadable": True,
                "is_free": False,
                "asset": {
                    "_class": "asset",
                    "id": 53841,
                    "asset_type": "ImportContent",
                    "title": "Ella Y Yo",
                    "created": "2012-01-04T10:12:51Z",
                },
                "sort_order": 0,
                "can_be_previewed": False,
            },
            {
                "_class": "lecture",
                "id": 89860,
                "title": "Cineticket Internet ",
                "created": "2012-06-04T16:35:04Z",
                "description": "",
                "title_cleaned": "cineticket-internet",
                "is_published": True,
                "transcript": None,
                "is_downloadable": True,
                "is_free": False,
                "asset": {
                    "_class": "asset",
                    "id": 85146,
                    "asset_type": "E-Book",
                    "title": "Cineticket Internet ",
                    "created": "2012-06-04T16:35:04Z",
                },
                "sort_order": 0,
                "can_be_previewed": False,
            },
        ],
    }


@pytest.fixture
def public_curriculum_with_params():
    return {
        "count": 3,
        "next": "https://www.udemy.com/api-2.0/courses/12345/public-curriculum-items/?page=2&page_size=1",
        "previous": None,
        "results": [
            {
                "_class": "chapter",
                "id": 542756,
                "created": "2014-12-05T18:54:27Z",
                "sort_order": 4,
                "title": "My First Section",
                "description": None,
                "is_published": True,
            }
        ],
    }
